_BASE_: "Base-SparseInst.yaml"
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
  WEIGHTS: "/home/aiviz05/Projects/SparseInst/output/PillNet_March_10/model_final.pth"
  SPARSE_INST:
    DECODER:
      NAME: "BaseIAMDecoder"
      NUM_CLASSES: 1
  LORA:
    ENABLED: False
    RANK: 8
    ALPHA: 16.0
    BACKBONE: False
    ENCODER: True
    DECODER: True
DATASETS:
  TRAIN: ("pills_train",)
  TEST: ("pills_val",)
OUTPUT_DIR: "output/sparse_inst_r50_base"
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.00005        # Slightly increased for better adaptation
  STEPS: (12000, 13500)   # Drop earlier if the model converges quickly
  MAX_ITER: 15000
  WARMUP_ITERS: 1000      # Added for stability
  WEIGHT_DECAY: 0.05
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 1000